cloud:
  aws:
    credentials:
      access-key: AKIAR6XEY346D3QZBFGX
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: demospringboots3bucketmai

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 20MB
      max-request-size: 50MB

server:
  port: 9090
